dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/test_db
  username: postgres
  password: postgres
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test_db
    social:
      facebook:
        appId:
        appSecret: