dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/test_db
  username: postgres
  password: postgres
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update

spring.data:
  mongodb.host: localhost
  mongodb.port: 27017
  mongodb.database: test_db