dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://ec2-54-163-245-32.compute-1.amazonaws.com:5432/d7oar4ddplmm6a?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
  username: dhoqqhkwmukemi
  password: GzbNqjdyKZBrc3EAvmJkMi_zab
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update
  show_sql: true
  format_sql: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test_db
    social:
      facebook:
        appId: 1754468614840836
        appSecret: 0f982323513acb858d30dd0846fcfc63